export const COLLECT_INTEND_DATA = 'COLLECT_INTEND_DATA';
export const CLEAR_INTEND_DATA = 'CLEAR_INTEND_DATA';
export const CREATE_INTEND_REQUEST = 'CREATE_INTEND_REQUEST';
export const CREATE_INTEND_SUCCESSFULLY = 'CREATE_INTEND_SUCCESSFULLY';
export const CREATE_INTEND_FAILED = 'CREATE_INTEND_FAILED';
